version: "3"

services:
  web:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - .:/app

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    volumes:
      - data:/bitnami/mongodb

volumes:
  data:
