version: "3"

services:
  web:
    build: .
    # command: uvicorn app:app --host 0.0.0.0 --port 8080  --workers 1 --reload
    command: gunicorn app:app --workers 2  --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - .:/app

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    volumes:
      - data:/bitnami/mongodb
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./tests:/mnt/locust
    command: -f /mnt/locust/loadtest.py --master

  worker:
    image: locustio/locust
    volumes:
      - ./tests:/mnt/locust
    command: -f /mnt/locust/loadtest.py --worker --master-host master
volumes:
  data:
